### ISSUE TITLE
Investigate FOSS productivity tools

### ISSUE THREAD

**Issue by jorp** [rocky-linux/organization#9]
https://www.atlassian.com/software/views/open-source-license-request

**Comment by v0tti** [comment]
I am wondering if Atlassian is the correct toolkit as they will stop supporting their server products: https://www.atlassian.com/migration/journey-to-cloud

**Comment by maxadamo** [comment]
1. what would be the technical problem with GPL-2 and GPL-3 (and derivatives)? And what problem would a different type of license solve? 

1. Can a license avoid situations like this (with CentOS) to happen again? If the answer is "yes", that's probably the right license. 

1. on the other side, is a license prone to create such a situation from happening again and again? For instance the BSD type of license, will make this happen tomorrow again.

**Comment by maxadamo** [comment]
> I am wondering if Atlassian is the correct toolkit as they will stop supporting their server products: https://www.atlassian.com/migration/journey-to-cloud

@v0tti I think they're more interested in the "concept", rather then being Atlassian fellows. 
OS is like a big container, where you put stuff in, with different type of licenses. You may need to avoid that you can't run certain tools, because they'll infringe your license, and you may also need to avoid sneaky people from stealing your intellectual property (like it happens with BSD).

**Comment by kfiresmith** [comment]
-1 on any Atlassian reliance for Rocky Linux.  We've seen how they knife their paying on-prem customers; no way should we rely on anything from them regardless of the current license.

**Comment by pxdnbluesoul** [comment]
I have done this process before and can assist in the setup, there are some requirements like at least one public Jira.

**Comment by Addvilz** [comment]
Only if they provide us with custom license. We do not meet their requirements, since we don't have a product yet.

**Comment by pxdnbluesoul** [comment]
We do have multiple repos with multiple contributors and these requests are reviewed by hand, I would definitely give it a try and I would be surprised if we were not approved.

**Comment by Addvilz** [comment]
@pxdnbluesoul it's not about the fact we don't have repos, we don't have end product. So according to their FOSS terms, we are not compliant. They COULD approve us, but it's not at all granted.

Also, alternatives:

- https://www.openproject.org
- https://www.redmine.org
- Just stick with GitHub issues for now.

**Comment by lillolollo** [comment]
Why not gitlab Gnome use it https://gitlab.gnome.org/

**Comment by dadangnh** [comment]
I think gitlab is good alternative, [Gnome](https://gitlab.gnome.org/GNOME), [KDE](https://invent.kde.org/kde), [FreeDesktop](https://gitlab.freedesktop.org/) and others migrating their environment to self hosted gitlab

**Comment by Addvilz** [comment]
GitLab is not a project/product management tool. You CAN do it using GitLab, but it is not very efficient to do so.

**Comment by jorp** [comment]
I changed the title to more accurately reflect what we're trying to accomplish. Thanks for the feedback

**Comment by maxadamo** [comment]
> GitLab is not a project/product management tool. You CAN do it using GitLab, but it is not very efficient to do so.

Why not? 
1. It has an issue tracker.
2. It has a wiki, where the documentation is naturally linked with the project. 
3. It has a kanban board (it lacks the drag 'n drop, but you don't want to pay a license to move the kanban items around)
4. It doesn't require integration with an external git to reference Merge requests with ticket. 
5. It's not awful to manage on premises like any of the Atlassian products (this option is gonna end soon)

What else do you need to manage a product?

**Comment by Addvilz** [comment]
In a few words, you are considering just the developer perspective, not whoever does/will manage the product and projects. And as I said, just because you can and someone does use these tools does not mean it's a good or optimal way of doing it. And we can't discard alternatives simply because someone else is already doing something, we have to consider context.

Let's move discussion to #rocky-infra on Slack. Otherwise this ticket will become unmanageable. Ping me there please if you want to chat further.

**Comment by BenAgner** [comment]
I agree that Atlassian is needed organizationally, and they have been a big supporter of OSS in the past.  It helps when breaking the projects up into manageable pieces and rolling that effort up unto a usable roadmap.  GitLab is getting there, but it doesn't shine a candle to the real project management aspects of JIRA and the rest of the Atlassian suite.

I have a lot of experience with Atlassian, and would be happy to help manage the instance if we decide to use them.

**Comment by Wild1145** [comment]
I've looked at alternatives to Jira in the past and ultimately always ended up finding my way back there... 

If you were only looking to run a fairly small team on a single piece of software (scaled however, but 1 team = 1 software) then Gitlab / other tools tend to work reasonably well. However, the reason Atlassian can fuck over everyone on their server pricing is because they know for their project management tools they're one of the best in the business, and to be honest for a project like this it feels like it's the right way to go, especially if you can get a free license (ideally a cloud hosted one at that)... Allows you to still have project isolation for your tickets while enabling developers and other end-users to have meaningful kanban / scrum boards to actually work from rather than just trying to work out what's good / what's not to work on next. 

Slightly biased because I've been supporting Atlassian applications for the last few years in every job I've ended up at but it does tend to be pretty good...

**Comment by y0rune** [comment]
We can use also the https://www.phacility.com/phabricator/ ;)

**Comment by maxadamo** [comment]
@Wild1145 this is definitely not a small team or a small project (and they're using an old version of Gitlab): 
https://gitlab.gnome.org/groups/GNOME/-/boards

**Comment by BenAgner** [comment]
> @Wild1145 this is definitely not a small team or a small project (and they're using an old version of Gitlab):
> https://gitlab.gnome.org/groups/GNOME/-/boards

I don't personally think a 25K issue backlog in a single board is a "usable" solution, but I'd be interested to hear from people at GNOME to see how they like it.

**Comment by Wild1145** [comment]
@maxadamo Appreciate that, but with 22K+ open issues, that makes it a pretty tricky Kanban board to use and to manage generally... To me with a background as an agile scrum master that doesn't look (At least to me) like a super productive way of working if you wanted people to be able to pick work up, and also to be able to ensure that things like bugs are effectively triaged and prioritised effectively along with just your entire backlog being put into some sort of ordered state so you know what you can pick off and when... 

Not saying it's not going to work, but it feels like a very "painful" way of doing it when generally speaking you want the Kanban board to be somewhere people can just get on and work rather than spend 20mins going through things trying to work out what's what.

**Comment by maxadamo** [comment]
@BenAgner this is the "Board per group". You have single boards per projects. 
The group board is used to have an overview, and you're not gonna work with it, to move issues around the kanban.

**Comment by Addvilz** [comment]
@maxadamo please stop :( We heard you. Let's keep focus here. There is no need to argue semantics for miles.

**Comment by maxadamo** [comment]
@Addvilz stop showing the benefits that you guys are not noticing? We only need to note down the downsides? 
Feel also free to delete my comments.

**Comment by timelordx** [comment]
Please, work together with these guys, if possible:

- [Announcing Open-sourced & Community-Driven RHEL Fork by CloudLinux](https://blog.cloudlinux.com/announcing-open-sourced-community-driven-rhel-fork-by-cloudlinux)

**Comment by BenAgner** [comment]
> I am wondering if Atlassian is the correct toolkit as they will stop supporting their server products: https://www.atlassian.com/migration/journey-to-cloud

They're only dropping support for "server" not "data center".  Essentially you no longer get perpetual-use licenses - gotta pay annually if you wanna run on-prem.

**Comment by hbjydev** [comment]
> stop showing the benefits that you guys are not noticing? We only need to note down the downsides?
@maxadamo No, that's not what he's saying. What he's _saying_ is that we shouldn't disregard the Atlassian (or other such company) offerings, and that the majority of us already know what Gitlab could provide. What we want is a system that we can easily manage, keep progress in the public view, and allows us to organize ourselves efficiently and with as much detail as we deem fit.

I'm absolutely with @Addvilz on this, GitLab to me, being someone who maintains a Gitlab instance for work, is **not** a project management feature, especially not on the free tier. While the GNOME project might be fine with their solution, that does not speak for us as a project, nor does it speak for the core group of members seeking to control and structure the work that goes into this.

I hope we can proceed with no hard feelings, in a way that is _constructive_, not damaging/detrimental to the community.

**Comment by mstg** [comment]
I agree with @hbjydev on this. There are many alternatives but we should not disregard Atlassian tools as there are many that are familiar with them. For bug tracking+code review, I would suggest Bugzilla+Gerrit as that is a very good combo. Although that may not be a good fit for project management.

**Comment by brianclemens** [comment]
Speaking as the project manager, this issue is something I hope gets resolved quickly. Our interim solutions have me bouncing around quite a bit and often finding out there are items dropped. I am considering [OpenProject](https://www.openproject.org/). The Linux Foundation and a few other large names use it, so it's not some dumpy pet project that we'll end up having to support later on. It has a FOSS version with a good featureset that we'll be able to integrate with our future account infra. I am currently playing with it in a VM for evaluation. I like what I see so far.

**Comment by maxadamo** [comment]
> @maxadamo please stop :( We heard you. Let's keep focus here. There is no need to argue semantics for miles.

Can I kindly ask the owner of the repo to delete this rude message (and I'll delete my subsequent messages as well)? 
It will be really appreciated. Thanks in advance.

**Comment by hbjydev** [comment]
> Can I kindly ask the owner of the repo to delete this rude message

@maxadamo That's not a rude message, he was trying to say that he's taken your point on board but he still disagrees. I'm not removing his message, nor will any other admin here.

**Comment by maxadamo** [comment]
@hbjydev, no. You miss part of the conversation on Slack, where he was very rude, but I don't to make a flame here and play copye and paste. that why I'm kindly asking to delete those message and I delete mines.

**Comment by maxadamo** [comment]
Shall I go the the code of conduct to check if this behavior is acceptable? Is there a code of conduct in place already?

**Comment by maxadamo** [comment]
to me it's clear that this language is abusive on an issue tracker. He could have used other ways to reply to my message. Below is a piece of code of conduct from Fedora (which is piece of common sense in such environment): 
![immagine](https://user-images.githubusercontent.com/1710103/101904239-d561ae00-3bb5-11eb-858d-a4bc96871ddd.png)

**Comment by maxadamo** [comment]
don't put this guys into the admin teams, as you'll get soon into troubles. My two cents.

**Comment by Addvilz** [comment]
Following consensus reached in infra, we are going to use OpenProject.
